package discord.discord1;

public enum UIResponseCode {
    OK,
    YES,
    NO,
    DUPLICATE_USERNAME,
    EMPTY,
    NUMBER_LETTER,
    SIX_LETTER,
    EIGHT_LETTER,
    LETTER,
    NUMBER,
    INVALID_EMAIL,
    INVALID_TEL,
    NO_USER,
    NOT_EXIST, NOT_IN_SERVER, LIMIT_BEFORE, BAN_BEFORE, BEFORE_IN_ROLE, NOT_CHANGE, DUPLICATED, IS_EXISTS, INVALID_PASSWORD

}
