package discord.discord1;

public enum UIRequestCode {
    SIGN_UP,
    LOG_IN,
    LOG_OUT,
    CHANGE_PASSWORD,
    GET_PHONE_NUMBER,
    REMOVE_PHONE_NUMBER,
    CHANGE_PHONE_NUMBER,
    GET_EMAIL,
    CHANGE_EMAIL,
    GET_USERNAME,
    CHANGE_USERNAME,
    GET_STATUS,
    SELECT_PROFILE,
    GET_SERVER_USERS,
    CHANGE_STATUS,
    SEE_CHANNELS
}