package discord.discord1;

public enum UIResponseCode {
    OK,
    YES,
    NO,
    DUPLICATE_USERNAME,
    EMPTY,
    NUMBER_LETTER,
    SIX_LETTER,
    EIGHT_LETTER,
    LETTER,
    NUMBER,
    INVALID_EMAIL,
    INVALID_TEL,
    NO_USER,
    INVALID_PASSWORD,
    SHOW_LIST,
    BEFORE_FRIEND,
    BEFORE_REQUEST,
    FRIEND_NOT_FOUND,
    OWN_REQUEST,
    REQUEST_AGAIN,
    NOT_EXIST,
    IS_EXISTS,
    NOT_CHANGE,
    DUPLICATED,
    NOT_IN_SERVER,
    LIMIT_BEFORE,
    BAN_BEFORE

}
